// SPDX-License-Identifier: AGPL-3.0-or-later

import {PORCH_DESKTOP_CHANNEL, PORCH_DESKTOP_PRODUCT} from '@electron/common/PorchProduct';

export const DESKTOP_APP_NAME = PORCH_DESKTOP_CHANNEL.appName;
export const MACOS_BUNDLE_ID = PORCH_DESKTOP_CHANNEL.appId;
export const LINUX_DESKTOP_ENTRY_ID = PORCH_DESKTOP_CHANNEL.linuxPackageName;
export const WINDOWS_SHORTCUT_AUTHOR = PORCH_DESKTOP_PRODUCT.companyName;
const WINDOWS_VELOPACK_ID = PORCH_DESKTOP_CHANNEL.packageName;
export const WINDOWS_APP_USER_MODEL_ID = PORCH_DESKTOP_CHANNEL.windowsAppUserModelId;
export const WINDOWS_LEGACY_APP_USER_MODEL_IDS = [`velopack.${WINDOWS_VELOPACK_ID}`];
export const WINDOWS_TOAST_ACTIVATOR_CLSID = PORCH_DESKTOP_CHANNEL.windowsToastActivatorClsid;
